version: "2"
services:
  app:
    build: ./flask-server
    container_name: flask_sever
    links:
      - db
    ports:
      - "5000:5000"

  db:
    container_name: mysql_db
    image: mysql:8
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fun
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./db-backup:/docker-entrypoint-initdb.d/:ro